### ISSUE TITLE
Save checkpoint and make_dir problem

### ISSUE THREAD

**Issue by YingJieYang1997** [guanyingc/DeepHDRVideo#21]
Hi,
Thanks to the author for the code, it really help me a lot. In the process of retraining the model, we set make_dir as True.We only modify dataset_dir in train_opt.py. In the code, an error occurred in the creation the saving folder. The error is as follows:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    log  = logger.Logger(args)
  File "I:\DeepHDRVideo-master\utils\logger.py", line 29, in __init__
    self._setup_dirs(args)
  File "I:\DeepHDRVideo-master\utils\logger.py", line 76, in _setup_dirs
    self.log_fie = open(file_dir, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'logdir/syn_vimeo_dataset\\ICCV\\11-28,spynet_2triple,weight_net,LReLU,hdr3E_flow_model,kaiming,l1,cm_d-256,cr_h-256,ht_r-0.9,ba_h-16,in_r-0.0001,in_ldr,sc_h-320,concat\\11-28,spynet_2triple,weight_net,LReLU,hdr3E_flow_model,kaiming,l1,cm_d-256,cr_h-256,ht_r-0.9,ba_h-16,in_r-0.0001,in_ldr,sc_h-320,concat,14:47:07'

Whether my settings are wrong. Hope to get your help, thank you!

**Comment by guanyingc** [comment]
Hi, it seems that you are using the windows system? I can see that the path name contains both '/' and '\'. 

We only tested this code in linux system. You might need to set the path correctly in windows.

**Comment by YingJieYang1997** [comment]
Yes, we run this code on Windows. Perhaps the difference between linux and windows systems caused this error.
In logger.py, could you tell us which folder should file_dir point to in line 75 " file_dir=os.path.join (args. log_dir, '% s,% s'% (dir_name, date_now. strftime ('% H:% M:% S')) "  ?

In other words,in line 76 "self.log_fie = open(file_dir, 'w')" , which floder should  self.log_fie point to ?**“logdir/syn_vimeo_dataset\ICCV\11-28,spynet_2triple,weight_net,LReLU,hdr3E_flow_model,kaiming,l1,cm_d-256,cr_h-256,ht_r-0.9,ba_h-16,in_r-0.0001,in_ldr,sc_h-320,concat“**  ,  **"...\checkpointdir"** or other floder ?

Hope to get your help, thank you!

**Comment by guanyingc** [comment]
Hi, I think the problem might be caused by the --save_root 'logdir/'. Try to use 'logdir\' or just 'logdir'.
https://github.com/guanyingc/DeepHDRVideo/blob/b9686676122f1eb879673448c78f853ad8c523a3/options/base_opts.py#L112
